/**
 * Physics-first motion system — the web port of convey's `ConveyMotion`.
 *
 * Every spring here has a name that describes what it communicates to the user,
 * not how it behaves mathematically. "Snappy" because the user feels their touch
 * acknowledged immediately. "Deliberate" because slow motion signals weight and
 * consequence. "Elastic" because the overshoot communicates playfulness and life.
 *
 * The parameters are deliberate and are ported bit-for-bit from `convey`'s
 * `tokens/ConveyMotion.kt` (stiffness/dampingRatio pairs). Do not adjust them for
 * aesthetic reasons — if you need different motion, add a new named entry to your
 * `ConveyGrammar` instead of hand-tuning one of these.
 *
 * CSS has no native spring easing, so every `SpringSpec` here is realized as a CSS
 * `linear()` easing function (Baseline 2023+) generated by sampling a damped
 * harmonic oscillator — see `springToLinearEasing`. This keeps animation fully
 * declarative (a CSS `transition`/`animation` timing-function string), with no
 * per-frame JS stepping required, matching how a `SpringSpec` is just data until
 * Compose's own animation runtime samples it.
 */

/** A spring's physical parameters — identical fields to Compose's `SpringSpec`. */
export interface SpringSpec {
  readonly kind: 'spring'
  readonly stiffness: number
  readonly dampingRatio: number
}

/** A duration + CSS cubic-bezier easing pair — the web equivalent of Compose's `TweenSpec`. */
export interface TweenSpec {
  readonly kind: 'tween'
  readonly durationMillis: number
  /** A valid CSS `cubic-bezier(...)` or keyword easing string. */
  readonly easing: string
}

/** No animation. Error states interrupt; they do not ease. */
export interface SnapSpec {
  readonly kind: 'snap'
}

export type AnimationSpec = SpringSpec | TweenSpec | SnapSpec

function spring(stiffness: number, dampingRatio: number): SpringSpec {
  return { kind: 'spring', stiffness, dampingRatio }
}

function tween(durationMillis: number, easing: string): TweenSpec {
  return { kind: 'tween', durationMillis, easing }
}

function snap(): SnapSpec {
  return { kind: 'snap' }
}

export const ConveyMotion = {
  // ── Springs — named for what they communicate ─────────────────────────────

  /**
   * Immediate acknowledgment. No perceptible latency between touch and response.
   * Use for: pressed states, toggle switches, immediate feedback.
   * Communicates: "I heard you."
   */
  Snappy: spring(620, 0.74),

  /**
   * Purposeful but unhurried. Confident motion that doesn't rush.
   * Use for: navigation, layout shifts, most state transitions.
   * Communicates: "Something changed, and this is where you are now."
   */
  Standard: spring(380, 0.82),

  /**
   * Slow and weighted. Implies the element has mass or consequence.
   * Use for: revealing important content, dialogs, heavy data.
   * Communicates: "Pay attention. This matters."
   */
  Deliberate: spring(180, 0.88),

  /**
   * Moderate overshoot. Suggests life, personality, delight.
   * Use SPARINGLY. Reserve for hero moments and first-run experiences.
   * Communicates: "This system is alive and glad you're here."
   * Warning: overuse destroys the effect. One elastic spring per screen, maximum.
   */
  Elastic: spring(280, 0.38),

  /**
   * Strong overshoot. Maximum expressiveness.
   * Use ONCE per significant user achievement. Not per screen. Per achievement.
   * Communicates: "You did something important. The system is celebrating with you."
   */
  Heroic: spring(220, 0.26),

  // ── Tweens — for cases where duration matters more than physics ───────────

  /**
   * Fast linear exit. Content leaving doesn't need spring — it just goes.
   * Springs on exit slow down the thing the user has already moved past.
   */
  Exit: tween(180, 'cubic-bezier(0.4, 0, 1, 1)'), // FastOutLinearInEasing

  /**
   * Deliberate entrance for content that wants to be read.
   * Decelerates into position — fast start, slow settle.
   */
  Enter: tween(300, 'cubic-bezier(0, 0, 0.2, 1)'), // LinearOutSlowInEasing

  /**
   * Error states do not animate. They interrupt.
   * An animated error message says "this error is part of the flow."
   * A snap says "stop. something is wrong."
   */
  Interrupt: snap(),

  // ── Duration scale (milliseconds) ─────────────────────────────────────────

  Duration: {
    Short1: 50,
    Short2: 100,
    Short3: 150,
    Short4: 200,

    Medium1: 250,
    Medium2: 300,
    Medium3: 350,
    Medium4: 400,

    Long1: 450,
    Long2: 500,
    Long3: 550,
    Long4: 600,

    ExtraLong1: 700,
    ExtraLong2: 800,
    ExtraLong3: 900,
    ExtraLong4: 1000,
  },

  // ── Easing curves ─────────────────────────────────────────────────────────

  Easing: {
    /** Standard curve. Appropriate for most transitions. */
    Standard: 'cubic-bezier(0.4, 0, 0.2, 1)',

    /** Emphasized. For elements that should draw attention. */
    Emphasized: 'cubic-bezier(0.2, 0, 0, 1)',

    /** Decelerate into final position. For incoming elements. */
    EmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',

    /** Accelerate out of view. For departing elements. */
    EmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  },
} as const

// ── Spring → CSS ────────────────────────────────────────────────────────────

/** True if this spring will overshoot its target before settling. */
export function isElastic(s: SpringSpec): boolean {
  return s.dampingRatio < 1
}

/** True if this spring is critically damped (no overshoot, fastest possible settling). */
export function isCriticallyDamped(s: SpringSpec): boolean {
  return s.dampingRatio >= 1
}

/** Estimated time to settle within `tolerance` of the target, in milliseconds. */
export function estimatedDurationMs(s: SpringSpec, tolerance = 0.01): number {
  if (s.dampingRatio >= 1) return Math.round(3000 / s.stiffness)
  const omega = Math.sqrt(s.stiffness)
  const decay = s.dampingRatio * omega
  if (decay === 0) return Number.MAX_SAFE_INTEGER
  return Math.round((-Math.log(tolerance) / decay) * 1000)
}

/**
 * Samples a unit-mass damped harmonic oscillator (the same model Compose's `spring()`
 * animates) and returns a CSS `linear()` easing function string reproducing that curve
 * over `durationMs` (default: this spring's own settle time, see `estimatedDurationMs`).
 *
 * Usage:
 * ```ts
 * el.style.transitionTimingFunction = springToLinearEasing(ConveyMotion.Snappy)
 * el.style.transitionDuration = `${estimatedDurationMs(ConveyMotion.Snappy)}ms`
 * ```
 *
 * `linear()` is Baseline 2023 (Chrome 113+, Firefox 112+, Safari 17.2+) — the only CSS
 * timing-function primitive expressive enough to encode an overshooting spring without
 * falling back to per-frame JavaScript. `steps` controls fidelity vs. string size; 24 is
 * enough for a springs this system uses (short, few-oscillation curves) to look correct
 * at typical UI sizes and durations.
 */
export function springToLinearEasing(s: SpringSpec, durationMs?: number, steps = 24): string {
  const duration = durationMs ?? estimatedDurationMs(s)
  const omega0 = Math.sqrt(s.stiffness)
  const zeta = s.dampingRatio

  const positionAt = (tMs: number): number => {
    const t = tMs / 1000
    if (zeta >= 1) {
      // Critically/over-damped: no oscillation.
      const omegaD = omega0 * Math.sqrt(zeta * zeta - 1)
      if (zeta === 1 || omegaD === 0) {
        return 1 - Math.exp(-omega0 * t) * (1 + omega0 * t)
      }
      const r1 = -omega0 * (zeta - Math.sqrt(zeta * zeta - 1))
      const r2 = -omega0 * (zeta + Math.sqrt(zeta * zeta - 1))
      const c2 = -r1 / (r2 - r1)
      const c1 = 1 - c2
      return 1 - (c1 * Math.exp(r1 * t) + c2 * Math.exp(r2 * t))
    }
    // Underdamped: decaying oscillation toward 1.
    const omegaD = omega0 * Math.sqrt(1 - zeta * zeta)
    const envelope = Math.exp(-zeta * omega0 * t)
    const phase = Math.cos(omegaD * t) + (zeta * omega0) / omegaD * Math.sin(omegaD * t)
    return 1 - envelope * phase
  }

  const stops: string[] = []
  for (let i = 0; i <= steps; i++) {
    const tMs = (i / steps) * duration
    const value = positionAt(tMs)
    stops.push(value.toFixed(4))
  }
  return `linear(${stops.join(', ')})`
}

/**
 * Resolves any `AnimationSpec` to a CSS `{ duration, easing }` pair ready for
 * `element.style.transitionDuration`/`transitionTimingFunction`, or for a Web Animations
 * API `KeyframeEffect` options object.
 */
export function toCss(specValue: AnimationSpec): { durationMs: number; easing: string } {
  switch (specValue.kind) {
    case 'spring':
      return { durationMs: estimatedDurationMs(specValue), easing: springToLinearEasing(specValue) }
    case 'tween':
      return { durationMs: specValue.durationMillis, easing: specValue.easing }
    case 'snap':
      return { durationMs: 0, easing: 'step-end' }
  }
}
